name: Docker Build CI for PlaqView

on:
  push:
    branches:
    - 'main' # change this whenever you switch branch

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }} # new 12-07-21
          password: ${{ secrets.QUAY_PASSWORD }} # new 12-07-21
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: true
          tags: quay.io/wfma888/plaqview:stable # change this tag to whichever to match container-image
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  Notify:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      -
        name: Install awscli
        run: sudo pip install --upgrade pip && pip install awscli
      -
        name: Send SQS message
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}        # also change '--mesage-body to same' for different containers
        run: aws sqs send-message --queue-url 'https://queue.amazonaws.com/474683445819/dcos-refresh' --message-body 'cphg/millerlab-plaqview' || exit 1;
        
        # message-body needs to match serviceID
