name: Docker Build CI for PlaqView

on:
  push:
    branches:
    - 'master'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: true
          tags: ghcr.io/MillerLab-CPHG/plaqview:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  Notify:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      -
        name: Install awscli
        run: sudo pip install --upgrade pip && pip install awscli
      -
        name: Send SQS message
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: aws sqs send-message --queue-url 'https://queue.amazonaws.com/474683445819/dcos-refresh' --message-body '/cphg/millerlab-plaqview' || exit 1;
